# Messages Configuration
messages:
  command:
    player-only: "&cThis command can only be used by players."
    no-permission: "&cYou don't have permission to use this command."
    reload:
      success: "&aConfig reloaded."
    help:
      header: "&6===== LeDatOrder Help ====="
      order: "&e/order &7- Open the main order GUI"
      my: "&e/order my &7- Open your orders GUI"
      reload: "&e/order reload &7- Reload the config"

  # Order Creation Messages
  order:
    creation:
      success: "&aOrder created successfully! (&e%current%&a/&e%max%&a)"
      amount-invalid: "&cAmount must be greater than 0."
      price-invalid: "&cPrice must be greater than 0."
      limit-reached: "&cBạn đã đạt giới hạn số lượng order (&e%max%&c). Hãy hoàn thành hoặc hủy một số order hiện tại."
      insufficient-money: "&cYou don't have enough money to create this order. You need %amount%"
      insufficient-points: "&cYou don't have enough points to create this order. You need %amount%"
      payment-failed: "&cPayment failed! Please try again."
      fee-charged-vault: "&aYou have been charged &e%fee% &afor creating this order."
      fee-charged-points: "&aYou have been charged &e%fee% &afor creating this order."
      payment-success: "&aYou have paid &e%amount% &afor this order."
      broadcast: "&6%player% &avừa tạo đơn hàng: &e%amount%x %material% &a(&e%price%&a mỗi món, tổng &e%total%&a, &e%currency%&a)"
    cancel:
      cannot: "&cKhông thể hủy đơn hàng này. Có thể đơn đã hoàn thành hoặc không tồn tại."
      refund: "&aĐã hoàn trả &e%amount% &avề tài khoản của bạn."
      items-returned: "&aBạn đã nhận lại &e%amount% %material%&a từ đơn hàng."
      items-missing: "&eCòn &6%amount% %material%&e không thể hoàn trả do thiếu dữ liệu đóng góp."
      success: "&aOrder has been cancelled."
      success-full: "&aĐơn hàng đã được thu hồi sau khi hoàn thành 100%. Tất cả vật phẩm đã được gửi lại cho bạn."
      success-partial: "&aĐơn hàng đã được thu hồi. Bạn nhận lại số vật phẩm đã được giao và số tiền còn dư."
      success-empty: "&aĐơn hàng đã được thu hồi. Toàn bộ số tiền đã được hoàn trả cho bạn."
      contributor-refund: "&aBạn đã nhận lại &e%amount% %material%&a từ một đơn hàng bị hủy."
    collect:
      none: "&cNo items available to collect."
      partial: "&aĐã nhận &e%collected% %material%&a. Phần còn lại đã rơi xuống đất do túi đồ đầy."
      success: "&aĐã nhận &e%amount% %material%!"
      completed: "&aĐơn hàng đã hoàn thành và được xóa khỏi hệ thống."
    completed-owner: "&aĐơn hàng %material% đã hoàn thành và được xóa khỏi hệ thống!"

  # Currency Messages
  currency:
    vault-unavailable: "&cVault is not available!"
    playerpoints-unavailable: "&cPlayerPoints is not available!"
    no-system-available: "&cNo currency system is available!"
    vault-unavailable-switch: "&cVault is not available! Using PlayerPoints instead."
    playerpoints-unavailable-switch: "&cPlayerPoints is not available! Using Vault instead."
    type-changed: "&aCurrency type changed to: &e%type%"

  # Input Messages
  input:
    amount-prompt: "&aPlease enter the amount in chat:"
    price-prompt: "&aPlease enter the price per item in chat:"
    search-prompt: "&aPlease enter search term in chat:"
    amount-set: "&aAmount set to &e%amount%"
    price-set: "&aPrice set to &e%price%"
    material-set: "&aMaterial set to &e%material%"
    search-result: "&aKết quả tìm kiếm: &e%search%"
    search-cleared: "&aĐã xóa tìm kiếm."
    invalid-number: "&cInvalid number format. Please enter a valid number."
    amount-invalid: "&cAmount must be greater than 0."
    price-invalid: "&cPrice must be greater than 0."

  material-select:
    selected: "&aĐã chọn vật liệu: &e%material%"

  # Sort and Filter Messages
  sort:
    changed: "&aSắp xếp theo: &e%type%"

  filter:
    changed: "&aLọc theo: &e%type%"

  # Delivery Messages
  delivery:
    self-delivery: "&cBạn không thể giao đồ cho chính mình!"
    success: "&aSuccessfully delivered %amount% %material% to %player%'s order!"
    payment-received: "&aYou received %amount% for delivering items!"
    owner-update: "&a%player% đã giao &e%amount% %material%&a. Đã chi: &e%payment%&a."
    order-filled: "&aĐơn hàng đã nhận đủ số lượng yêu cầu."
    owner-complete: "&aĐơn hàng %material% của bạn đã hoàn thành! Hãy vào /order để nhận."
    excess-returned: "&aĐã trả lại &e%amount% %material%&a vượt quá số lượng yêu cầu."

  refund:
    received: "&aBạn đã nhận lại &e%amount% &avật phẩm từ các đơn hàng bị hủy."

# GUI Configuration
gui:
  # Main Order GUI
  order:
    title: "&6Orders (Page %page%)"
    size: 54
    
    order-item:
      display-name: "&6%player%'s Order"
      lore:
        - "&f%type%"
        - "&a%price%&f/1 item"
        - " "
        - "&a%revived%/%required% &7Delivered"
        - "&a%paid%/%total_paid% &7Paid"
        - " "
        - "&fNhấn để giao đồ cho &b%player%"
    
    sort-item:
      material: CAULDRON
      display-name: "&6Sort"
      slot: 47
    
    filter-item:
      material: HOPPER
      display-name: "&6Filter"
      slot: 48
    
    refresh-item:
      material: MAP
      display-name: "&6Refresh"
      lore:
        - "&7Làm mới GUI"
      slot: 49
    
    search-item:
      material: OAK_SIGN
      display-name: "&6Tìm kiếm"
      lore:
        - "&7Tìm kiếm material nhanh"
      slot: 50
    
    create-item:
      material: DROPPER
      display-name: "&6Tạo Order"
      lore:
        - "&7Mở GUI tạo order mới"
      slot: 51
    
    previous-page-item:
      material: ARROW
      display-name: "&6Trang trước"
      slot: 45
    
    next-page-item:
      material: ARROW
      display-name: "&6Trang sau"
      slot: 53
  
  # My Order GUI
  my-order:
    title: "&6Your Orders"
    size: 36
    
    order-item:
      display-name: "&6%player%'s Order"
      lore:
        - "&a%amount% &f%material%"
        - "&a%price% per item"
        - "&7Currency: &e%currency%"
        - " "
        - "&e%received%/%required% &7Delivered"
        - "&e%paid%/%total% &7Paid"
    
    border-item:
      material: BLACK_STAINED_GLASS_PANE
      display-name: " "
    
    create-item:
      material: MAP
      display-name: "&6Create New Order"
      lore:
        - "&7Click to create a new order"
      slot: 31
  
  # Order Manage GUI
  order-manage:
    title: "&6Manage Order"
    size: 27
    
    order-info-item:
      display-name: "&6Your Order: %material%"
      lore:
        - "&7Required: &a%required%"
        - "&7Price per item: &a%price%"
        - "&7Currency: &e%currency%"
        - " "
        - "&7Delivered: &e%received%/%required%"
        - "&7Paid: &e%paid%/%total%"
      slot: 13
    
    cancel-item:
      material: BARRIER
      display-name: "&cCancel Order"
      lore:
        - "&7Click to cancel this order"
      slot: 12
    
    collect-item:
      material: CHEST
      display-name: "&aCollect Items"
      lore:
        - "&7Click to collect delivered items"
        - "&7Available: &e%received%"
      slot: 14
  
  # Create Order GUI
  create-order:
    title: "&6Create Order"
    size: 27
    
    back-item:
      material: RED_STAINED_GLASS_PANE
      display-name: "&cBack"
      lore:
        - "&7Return to Your Orders"
      slot: 10
    
    material-item:
      material: STONE
      display-name: "&6Select Material"
      lore:
        - "&7Current: &a%material%"
        - "&7Click to change material"
      slot: 12
    
    amount-item:
      material: CHEST
      display-name: "&6Set Amount"
      lore:
        - "&7Current: &a%amount%"
        - "&7Click to set amount"
      slot: 13
    
    price-item:
      material: SUNFLOWER
      display-name: "&6Set Price Per Item"
      lore:
        - "&7Current: &a%price%"
        - "&7Click to set price"
      slot: 14
    
    currency-item:
      material: GOLD_INGOT
      display-name: "&6Currency Type"
      lore:
        - "&7Current: &a%currency%"
        - "&7Click to switch currency"
        - ""
        - "&7Vault Money: %vault_status%"
        - "&7PlayerPoints: %points_status%"
      slot: 22
    
    confirm-item:
      material: LIME_STAINED_GLASS_PANE
      display-name: "&aConfirm"
      lore:
        - "&7Material: &a%material%"
        - "&7Amount: &a%amount%"
        - "&7Price per item: &a%price%"
        - "&7Total cost: &a%total%"
        - "&7Currency: &e%currency%"
      slot: 16
  
  # Material Select GUI
  material-select:
    title: "&6Select Material"
    size: 54
    
    item:
      display-name: "&6%material%"
      lore:
        - "&7Click to select this material"
      
    filter-item:
      material: HOPPER
      display-name: "&6Filter Materials"
      slot: 47
    
    common-item:
      material: CHEST
      display-name: "&6Common Materials"
      lore:
        - "&7Show only common materials"
      slot: 48
    
    back-item:
      material: RED_STAINED_GLASS_PANE
      display-name: "&cBack"
      lore:
        - "&7Return to Create Order"
      slot: 49
    
    search-item:
      material: OAK_SIGN
      display-name: "&6Search Materials"
      lore:
        - "&7Click to search for materials"
      slot: 50
    
    previous-page-item:
      material: ARROW
      display-name: "&6Previous Page"
      slot: 45
    
    next-page-item:
      material: ARROW
      display-name: "&6Next Page"
      slot: 53
  
  # Order Delivery GUI
  order-delivery:
    title: "&6Order -> %player%"
    size: 45
    
    order-info:
      display-name: "&6%player%'s Order"
      lore:
        - "&7Required: &a%required% %material%"
        - "&7Price per item: &a%price%"
        - "&7Currency: &e%currency%"
        - ""
        - "&7Progress: &e%received%/%required%"
        - "&7Remaining: &c%remaining%"
        - ""
        - "&7Put items in the inventory to deliver"
      slot: 4
    
    back-item:
      material: BARRIER
      display-name: "&cBack to Orders"
      lore:
        - "&7Return to order list"
      slot: 40